### ISSUE TITLE
Disable caching in your audits

### ISSUE THREAD

**Issue by wooorm** [VincentKempers/performance-matters#3]
Your audits give a skewed view of what’s going on, because caching is still on (there’s a “disable cache” checkbox), meaning everything is super fast where it actually isn‘t!

**Comment by VincentKempers** [comment]
[i made a new audit and added a "after feedback title"](https://github.com/VincentKempers/performance-matters/blob/master/AUDIT.MD)

In those audits i made sure i disabled the cache. And showed the weird bug i encountered.
