### ISSUE TITLE
Images are rather high

### ISSUE THREAD

**Issue by wooorm** [VincentKempers/performance-matters#4]
While reading the audit, there’s a lot of images (good), but they’re rather high (bad, as i lose focus). I suggest making images in readme’s less high but still wide, to make readme’s more readable.

You can also use CMD+SHIFT+4, then press space, to capture a whole window on a mac, that includes the shadow around it, which makes for a nice visual difference and space around images as well!

**Comment by VincentKempers** [comment]
Thanks for the awesome tip (i use it for everything now). I didn't redo all the images with that. But to make it a bit pleasurable to read. I cropped the images (_things i cropped out were consoles and a lot of white space_). I hope this helps a bit
